# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'walkstreets-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for walkstreets-ios
pod 'GoogleMaps'
pod 'SwiftyJSON'
pod 'Spring', git: 'https://github.com/matbeich/Spring.git', branch: 'swift2_3'
pod 'Alamofire', '~> 3.5.0'
pod 'Mapbox-iOS-SDK', '~> 3.3.5'

end
