# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'walkstreets-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for walkstreets-ios
pod 'GoogleMaps'
pod 'SwiftyJSON'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
pod 'Alamofire', '~> 4.0'
pod 'Mapbox-iOS-SDK'


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

end
